# Generated by Django 4.2 on 2023-06-07 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_user_followers_user_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="followersuserprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                related_name="followinguserprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
