# Generated by Django 4.2 on 2023-06-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_alter_user_followers_alter_user_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="content",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
