# Generated by Django 4.2 on 2023-06-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0009_alter_posts_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="content",
            field=models.CharField(max_length=300),
        ),
    ]
