# Generated by Django 4.2 on 2023-06-08 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0011_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posts",
            old_name="likes",
            new_name="likecount",
        ),
        migrations.AddField(
            model_name="posts",
            name="users_who_liked",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
