# Generated by Django 4.2 on 2023-05-05 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auctionslistings_commentsauctions_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionslistings",
            name="products",
        ),
        migrations.AddField(
            model_name="auctionslistings",
            name="category",
            field=models.CharField(default="category", max_length=64),
        ),
        migrations.AddField(
            model_name="auctionslistings",
            name="description",
            field=models.CharField(default="description", max_length=300),
        ),
        migrations.AddField(
            model_name="auctionslistings",
            name="imageurl",
            field=models.CharField(default="imageurl", max_length=128),
        ),
        migrations.AddField(
            model_name="auctionslistings",
            name="startingbid",
            field=models.CharField(default="startingbid", max_length=64),
        ),
        migrations.AddField(
            model_name="auctionslistings",
            name="title",
            field=models.CharField(default="title", max_length=64),
        ),
        migrations.AlterField(
            model_name="auctionslistings",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auctionproduct",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productbid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="commentsauctions",
            name="comments",
            field=models.CharField(default="comments", max_length=300),
        ),
    ]
