# Generated by Django 4.2 on 2023-05-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_remove_auctionslistings_products_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="bid",
            new_name="bidproduct",
        ),
        migrations.AddField(
            model_name="bid",
            name="bidprice",
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
