# Generated by Django 4.2 on 2023-05-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_auctionslistings_startingbid"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionslistings",
            name="highest_bidder",
            field=models.CharField(default="None", max_length=64),
        ),
        migrations.AddField(
            model_name="auctionslistings",
            name="is_closed",
            field=models.BooleanField(default="False"),
        ),
        migrations.AlterField(
            model_name="bid",
            name="bidproduct",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bidobject",
                to="auctions.auctionslistings",
            ),
        ),
    ]
