# Generated by Django 4.2 on 2023-05-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_auctionslistings_highest_bidder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionslistings",
            name="highest_bid",
            field=models.IntegerField(default=0, max_length=64),
        ),
    ]
