# Generated by Django 4.2 on 2023-05-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_auctionslistings_highest_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentsauctions",
            name="product",
        ),
        migrations.AddField(
            model_name="commentsauctions",
            name="product",
            field=models.ManyToManyField(
                related_name="CommentsAuctions", to="auctions.auctionslistings"
            ),
        ),
    ]
