# Generated by Django 4.2 on 2023-05-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_auctionslistings_addedtowatchlist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionslistings",
            name="noofbids",
            field=models.IntegerField(default=0, max_length=64),
        ),
    ]
