# Generated by Django 4.2 on 2023-06-28 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_auctionslistings_noofbids"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentsauctions",
            name="commentcount",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="commentsauctions",
            name="comments",
            field=models.CharField(default="comments", max_length=700),
        ),
        migrations.RemoveField(
            model_name="commentsauctions",
            name="product",
        ),
        migrations.AddField(
            model_name="commentsauctions",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="CommentsAuctions",
                to="auctions.auctionslistings",
            ),
            preserve_default=False,
        ),
    ]
