# Generated by Django 4.2 on 2023-06-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_commentsauctions_commentcount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionslistings",
            name="addedtowatchlist",
        ),
        migrations.RemoveField(
            model_name="auctionslistings",
            name="watchlist_adder",
        ),
        migrations.AddField(
            model_name="user",
            name="watchlist_objects",
            field=models.ManyToManyField(
                default=None,
                related_name="watchlist_users",
                to="auctions.auctionslistings",
            ),
        ),
    ]
